name: Monitor Website

on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run monitoring script
        env: # Pass the Slack token securely
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: node monitoring.js
